// constants/templates.js

const templates = [
    {
        name: 'Grocery & Home',
        emoji: '🛒',
        description: 'Perfect for households tracking groceries and cleaning supplies.',
        isSystem: true,
        categories: [
            { name: 'Dairy', icon: '🥛', color: 'bg-blue-100' },
            { name: 'Produce', icon: '🥦', color: 'bg-green-100' },
            { name: 'Meat & Fish', icon: '🍗', color: 'bg-red-100' },
            { name: 'Bakery', icon: '🍞', color: 'bg-yellow-100' },
            { name: 'Cleaning', icon: '🧹', color: 'bg-teal-100' },
            { name: 'Snacks', icon: '🍿', color: 'bg-purple-100' },
        ],
        products: [
            { name: 'Whole Milk', category: 'Dairy', price: '4.99', unit: 'L', description: '2L bottle' },
            { name: 'Cheddar Cheese', category: 'Dairy', price: '5.49', unit: 'g', description: '500g block' },
            { name: 'Eggs', category: 'Dairy', price: '3.99', unit: 'dozen', description: '12 pack' },
            { name: 'Broccoli', category: 'Produce', price: '1.99', unit: 'g', description: '500g' },
            { name: 'Spinach', category: 'Produce', price: '2.49', unit: 'g', description: 'Baby spinach 200g' },
            { name: 'Bananas', category: 'Produce', price: '1.49', unit: 'kg', description: 'Per kg' },
            { name: 'Chicken Breast', category: 'Meat & Fish', price: '8.99', unit: 'kg', description: 'Boneless skinless' },
            { name: 'Salmon Fillet', category: 'Meat & Fish', price: '12.99', unit: 'kg', description: 'Atlantic salmon' },
            { name: 'Sourdough Bread', category: 'Bakery', price: '4.99', unit: 'loaf', description: 'Artisan loaf' },
            { name: 'Bagels', category: 'Bakery', price: '3.49', unit: 'pack', description: '6 pack' },
            { name: 'Dish Soap', category: 'Cleaning', price: '2.99', unit: 'ml', description: '500ml' },
            { name: 'Laundry Detergent', category: 'Cleaning', price: '11.99', unit: 'kg', description: '2kg box' },
            { name: 'Sponges', category: 'Cleaning', price: '3.49', unit: 'pack', description: '3 pack' },
            { name: 'Chips', category: 'Snacks', price: '2.99', unit: 'g', description: '200g bag' },
            { name: 'Granola Bars', category: 'Snacks', price: '4.99', unit: 'pack', description: '6 pack' },
        ],
    },

    {
        name: 'Baby & Kids',
        emoji: '👶',
        description: 'Everything you need for little ones at home.',
        isSystem: true,
        categories: [
            { name: 'Baby Food', icon: '🍼', color: 'bg-yellow-100' },
            { name: 'Hygiene', icon: '🧴', color: 'bg-blue-100' },
            { name: 'Toys', icon: '🧸', color: 'bg-purple-100' },
            { name: 'Clothing', icon: '👕', color: 'bg-green-100' },
            { name: 'Medicine', icon: '💊', color: 'bg-red-100' },
        ],
        products: [
            { name: 'Baby Formula', category: 'Baby Food', price: '24.99', unit: 'g', description: '800g tin' },
            { name: 'Pureed Carrots', category: 'Baby Food', price: '1.99', unit: 'g', description: '120g pouch' },
            { name: 'Rice Cereal', category: 'Baby Food', price: '5.99', unit: 'g', description: '454g box' },
            { name: 'Diapers', category: 'Hygiene', price: '29.99', unit: 'pack', description: '80 count' },
            { name: 'Baby Wipes', category: 'Hygiene', price: '7.99', unit: 'pack', description: '200 count' },
            { name: 'Baby Shampoo', category: 'Hygiene', price: '6.99', unit: 'ml', description: '400ml' },
            { name: 'Diaper Rash Cream', category: 'Hygiene', price: '8.99', unit: 'g', description: '113g tube' },
            { name: 'Infant Tylenol', category: 'Medicine', price: '12.99', unit: 'ml', description: '100ml' },
            { name: 'Saline Drops', category: 'Medicine', price: '6.99', unit: 'ml', description: '30ml' },
        ],
    },

    {
        name: 'Fitness & Health',
        emoji: '💪',
        description: 'Track your supplements, healthy foods and fitness gear.',
        isSystem: true,
        categories: [
            { name: 'Supplements', icon: '💊', color: 'bg-red-100' },
            { name: 'Healthy Snacks', icon: '🥜', color: 'bg-green-100' },
            { name: 'Equipment', icon: '🥊', color: 'bg-gray-100' },
            { name: 'Beverages', icon: '🧃', color: 'bg-blue-100' },
            { name: 'Meals', icon: '🍗', color: 'bg-yellow-100' },
        ],
        products: [
            { name: 'Whey Protein', category: 'Supplements', price: '49.99', unit: 'kg', description: '2kg bag' },
            { name: 'Creatine', category: 'Supplements', price: '24.99', unit: 'g', description: '300g' },
            { name: 'Multivitamins', category: 'Supplements', price: '19.99', unit: 'pack', description: '90 tablets' },
            { name: 'Omega 3', category: 'Supplements', price: '16.99', unit: 'pack', description: '60 capsules' },
            { name: 'Almonds', category: 'Healthy Snacks', price: '8.99', unit: 'g', description: '500g bag' },
            { name: 'Peanut Butter', category: 'Healthy Snacks', price: '6.99', unit: 'g', description: '500g jar' },
            { name: 'Granola', category: 'Healthy Snacks', price: '5.99', unit: 'g', description: '400g bag' },
            { name: 'Protein Bars', category: 'Healthy Snacks', price: '3.49', unit: 'each', description: 'Per bar' },
            { name: 'Resistance Bands', category: 'Equipment', price: '19.99', unit: 'set', description: '5 band set' },
            { name: 'Foam Roller', category: 'Equipment', price: '29.99', unit: 'each', description: 'Standard size' },
            { name: 'Electrolyte Drink', category: 'Beverages', price: '2.49', unit: 'ml', description: '500ml bottle' },
            { name: 'Protein Shake', category: 'Beverages', price: '3.99', unit: 'ml', description: 'Ready to drink' },
            { name: 'Oats', category: 'Meals', price: '4.99', unit: 'g', description: '1kg bag' },
            { name: 'Brown Rice', category: 'Meals', price: '3.99', unit: 'g', description: '1kg bag' },
            { name: 'Sweet Potato', category: 'Meals', price: '2.49', unit: 'kg', description: 'Per kg' },
        ],
    },

    {
        name: 'Office & Work',
        emoji: '🏢',
        description: 'Keep your workplace stocked with essentials.',
        isSystem: true,
        categories: [
            { name: 'Stationery', icon: '✏️', color: 'bg-yellow-100' },
            { name: 'Electronics', icon: '💻', color: 'bg-gray-100' },
            { name: 'Beverages', icon: '☕', color: 'bg-teal-100' },
            { name: 'Snacks', icon: '🍪', color: 'bg-purple-100' },
            { name: 'Cleaning', icon: '🧹', color: 'bg-blue-100' },
        ],
        products: [
            { name: 'Ballpoint Pens', category: 'Stationery', price: '4.99', unit: 'pack', description: '10 pack' },
            { name: 'Sticky Notes', category: 'Stationery', price: '3.99', unit: 'pack', description: '4 pads' },
            { name: 'A4 Paper', category: 'Stationery', price: '8.99', unit: 'pack', description: '500 sheets' },
            { name: 'Stapler', category: 'Stationery', price: '9.99', unit: 'each', description: 'Standard' },
            { name: 'USB Hub', category: 'Electronics', price: '24.99', unit: 'each', description: '4 port' },
            { name: 'HDMI Cable', category: 'Electronics', price: '12.99', unit: 'each', description: '2m cable' },
            { name: 'AA Batteries', category: 'Electronics', price: '7.99', unit: 'pack', description: '8 pack' },
            { name: 'Coffee Beans', category: 'Beverages', price: '14.99', unit: 'g', description: '500g bag' },
            { name: 'Green Tea', category: 'Beverages', price: '5.99', unit: 'pack', description: '50 bags' },
            { name: 'Instant Coffee', category: 'Beverages', price: '8.99', unit: 'g', description: '200g jar' },
            { name: 'Cookies', category: 'Snacks', price: '3.99', unit: 'pack', description: 'Assorted' },
            { name: 'Mixed Nuts', category: 'Snacks', price: '6.99', unit: 'g', description: '300g bag' },
            { name: 'Trash Bags', category: 'Cleaning', price: '5.99', unit: 'pack', description: '30 count' },
            { name: 'Hand Sanitizer', category: 'Cleaning', price: '4.99', unit: 'ml', description: '500ml' },
            { name: 'Paper Towels', category: 'Cleaning', price: '6.99', unit: 'roll', description: '6 rolls' },
        ],
    },

    {
        name: 'Blank / Custom',
        emoji: '⬜',
        description: 'Start from scratch and build your own categories and products.',
        isSystem: true,
        categories: [],
        products: [],
    },
];

export default templates;