import React from 'react';
import {AcademicCapIcon
    ,AdjustmentsHorizontalIcon
    ,AdjustmentsVerticalIcon
    ,ArchiveBoxArrowDownIcon
    ,ArchiveBoxXMarkIcon
    ,ArchiveBoxIcon
    ,ArrowDownCircleIcon
    ,ArrowDownLeftIcon
    ,ArrowDownOnSquareStackIcon
    ,ArrowDownOnSquareIcon
    ,ArrowDownRightIcon
    ,ArrowDownTrayIcon
    ,ArrowDownIcon
    ,ArrowLeftCircleIcon
    ,ArrowLeftEndOnRectangleIcon
    ,ArrowLeftOnRectangleIcon
    ,ArrowLeftStartOnRectangleIcon
    ,ArrowLeftIcon
    ,ArrowLongDownIcon
    ,ArrowLongLeftIcon
    ,ArrowLongRightIcon
    ,ArrowLongUpIcon
    ,ArrowPathRoundedSquareIcon
    ,ArrowPathIcon
    ,ArrowRightCircleIcon
    ,ArrowRightEndOnRectangleIcon
    ,ArrowRightOnRectangleIcon
    ,ArrowRightStartOnRectangleIcon
    ,ArrowRightIcon
    ,ArrowSmallDownIcon
    ,ArrowSmallLeftIcon
    ,ArrowSmallRightIcon
    ,ArrowSmallUpIcon
    ,ArrowTopRightOnSquareIcon
    ,ArrowTrendingDownIcon
    ,ArrowTrendingUpIcon
    ,ArrowTurnDownLeftIcon
    ,ArrowTurnDownRightIcon
    ,ArrowTurnLeftDownIcon
    ,ArrowTurnLeftUpIcon
    ,ArrowTurnRightDownIcon
    ,ArrowTurnRightUpIcon
    ,ArrowTurnUpLeftIcon
    ,ArrowTurnUpRightIcon
    ,ArrowUpCircleIcon
    ,ArrowUpLeftIcon
    ,ArrowUpOnSquareStackIcon
    ,ArrowUpOnSquareIcon
    ,ArrowUpRightIcon
    ,ArrowUpTrayIcon
    ,ArrowUpIcon
    ,ArrowUturnDownIcon
    ,ArrowUturnLeftIcon
    ,ArrowUturnRightIcon
    ,ArrowUturnUpIcon
    ,ArrowsPointingInIcon
    ,ArrowsPointingOutIcon
    ,ArrowsRightLeftIcon
    ,ArrowsUpDownIcon
    ,AtSymbolIcon
    ,BackspaceIcon
    ,BackwardIcon
    ,BanknotesIcon
    ,Bars2Icon
    ,Bars3BottomLeftIcon
    ,Bars3BottomRightIcon
    ,Bars3CenterLeftIcon
    ,Bars3Icon
    ,Bars4Icon
    ,BarsArrowDownIcon
    ,BarsArrowUpIcon
    ,Battery0Icon
    ,Battery100Icon
    ,Battery50Icon
    ,BeakerIcon
    ,BellAlertIcon
    ,BellSlashIcon
    ,BellSnoozeIcon
    ,BellIcon
    ,BoldIcon
    ,BoltSlashIcon
    ,BoltIcon
    ,BookOpenIcon
    ,BookmarkSlashIcon
    ,BookmarkSquareIcon
    ,BookmarkIcon
    ,BriefcaseIcon
    ,BugAntIcon
    ,BuildingLibraryIcon
    ,BuildingOffice2Icon
    ,BuildingOfficeIcon
    ,BuildingStorefrontIcon
    ,CakeIcon
    ,CalculatorIcon
    ,CalendarDateRangeIcon
    ,CalendarDaysIcon
    ,CalendarIcon
    ,CameraIcon
    ,ChartBarSquareIcon
    ,ChartBarIcon
    ,ChartPieIcon
    ,ChatBubbleBottomCenterTextIcon
    ,ChatBubbleBottomCenterIcon
    ,ChatBubbleLeftEllipsisIcon
    ,ChatBubbleLeftRightIcon
    ,ChatBubbleLeftIcon
    ,ChatBubbleOvalLeftEllipsisIcon
    ,ChatBubbleOvalLeftIcon
    ,CheckBadgeIcon
    ,CheckCircleIcon
    ,CheckIcon
    ,ChevronDoubleDownIcon
    ,ChevronDoubleLeftIcon
    ,ChevronDoubleRightIcon
    ,ChevronDoubleUpIcon
    ,ChevronDownIcon
    ,ChevronLeftIcon
    ,ChevronRightIcon
    ,ChevronUpDownIcon
    ,ChevronUpIcon
    ,CircleStackIcon
    ,ClipboardDocumentCheckIcon
    ,ClipboardDocumentListIcon
    ,ClipboardDocumentIcon
    ,ClipboardIcon
    ,ClockIcon
    ,CloudArrowDownIcon
    ,CloudArrowUpIcon
    ,CloudIcon
    ,CodeBracketSquareIcon
    ,CodeBracketIcon
    ,Cog6ToothIcon
    ,Cog8ToothIcon
    ,CogIcon
    ,CommandLineIcon
    ,ComputerDesktopIcon
    ,CpuChipIcon
    ,CreditCardIcon
    ,CubeTransparentIcon
    ,CubeIcon
    ,CurrencyBangladeshiIcon
    ,CurrencyDollarIcon
    ,CurrencyEuroIcon
    ,CurrencyPoundIcon
    ,CurrencyRupeeIcon
    ,CurrencyYenIcon
    ,CursorArrowRaysIcon
    ,CursorArrowRippleIcon
    ,DevicePhoneMobileIcon
    ,DeviceTabletIcon
    ,DivideIcon
    ,DocumentArrowDownIcon
    ,DocumentArrowUpIcon
    ,DocumentChartBarIcon
    ,DocumentCheckIcon
    ,DocumentCurrencyBangladeshiIcon
    ,DocumentCurrencyDollarIcon
    ,DocumentCurrencyEuroIcon
    ,DocumentCurrencyPoundIcon
    ,DocumentCurrencyRupeeIcon
    ,DocumentCurrencyYenIcon
    ,DocumentDuplicateIcon
    ,DocumentMagnifyingGlassIcon
    ,DocumentMinusIcon
    ,DocumentPlusIcon
    ,DocumentTextIcon
    ,DocumentIcon
    ,EllipsisHorizontalCircleIcon
    ,EllipsisHorizontalIcon
    ,EllipsisVerticalIcon
    ,EnvelopeOpenIcon
    ,EnvelopeIcon
    ,EqualsIcon
    ,ExclamationCircleIcon
    ,ExclamationTriangleIcon
    ,EyeDropperIcon
    ,EyeSlashIcon
    ,EyeIcon
    ,FaceFrownIcon
    ,FaceSmileIcon
    ,FilmIcon
    ,FingerPrintIcon
    ,FireIcon
    ,FlagIcon
    ,FolderArrowDownIcon
    ,FolderMinusIcon
    ,FolderOpenIcon
    ,FolderPlusIcon
    ,FolderIcon
    ,ForwardIcon
    ,FunnelIcon
    ,GifIcon
    ,GiftTopIcon
    ,GiftIcon
    ,GlobeAltIcon
    
    ,HandRaisedIcon
    ,HandThumbDownIcon
    ,HandThumbUpIcon
    ,HashtagIcon
    ,HeartIcon
    ,HomeIcon
    ,IdentificationIcon
    ,InboxArrowDownIcon
    ,InboxIcon
    ,InformationCircleIcon
    ,KeyIcon
    
    ,LifebuoyIcon
    ,LightBulbIcon
    
    ,LinkIcon
    ,ListBulletIcon
    
    ,LockClosedIcon
    ,LockOpenIcon
    ,MagnifyingGlassCircleIcon
    ,MagnifyingGlassIcon
    ,MapIcon
    ,MegaphoneIcon
    ,MicrophoneIcon
    ,MinusCircleIcon
    ,MinusIcon
    ,MoonIcon
    
    ,NewspaperIcon
    ,NoSymbolIcon
    ,PaperAirplaneIcon
    ,PaperClipIcon
    ,PauseCircleIcon
    ,PauseIcon
    ,PencilSquareIcon
    ,PencilIcon
    
    ,PhoneIcon
    ,PhotoIcon
    ,PlayCircleIcon
    ,PlayPauseIcon
    ,PlayIcon
    ,PlusCircleIcon
    ,PlusIcon
    ,PresentationChartBarIcon
    ,PresentationChartLineIcon
    ,PrinterIcon
    ,PuzzlePieceIcon
    ,QrCodeIcon
    ,QuestionMarkCircleIcon
    ,ReceiptPercentIcon
    
    
    ,RectangleGroupIcon
    ,RectangleStackIcon
    ,RocketLaunchIcon
    
    ,RssIcon
    
    
    ,ScaleIcon
    ,ScissorsIcon
    ,ShareIcon
    ,ShieldCheckIcon
    ,ShieldExclamationIcon
    
    ,SignalIcon
    
    ,SpeakerWaveIcon
    ,SpeakerXMarkIcon
    ,Square2StackIcon
    ,Square3Stack3DIcon
    
    
    ,Squares2X2Icon
    ,SquaresPlusIcon,
    StarIcon,
    StopCircleIcon,
    SunIcon,
    
    
    TableCellsIcon,
    TagIcon,
    
    
    
    
    TicketIcon,
    TrashIcon,
    TrophyIcon,
    TruckIcon,
    TvIcon,
    UserCircleIcon,
    UserGroupIcon,
    UserIcon,
    UsersIcon,
    VariableIcon,
    VideoCameraIcon,
    ViewColumnsIcon,
    ViewfinderCircleIcon,
    WifiIcon,
    WrenchIcon,
    XCircleIcon,
    XMarkIcon} from '@heroicons/react/24/outline'

export const heroIcons = {AcademicCapIcon
        ,AdjustmentsHorizontalIcon
        ,AdjustmentsVerticalIcon
        ,ArchiveBoxArrowDownIcon
        ,ArchiveBoxXMarkIcon
        ,ArchiveBoxIcon
        ,ArrowDownCircleIcon
        ,ArrowDownLeftIcon
        ,ArrowDownOnSquareStackIcon
        ,ArrowDownOnSquareIcon
        ,ArrowDownRightIcon
        ,ArrowDownTrayIcon
        ,ArrowDownIcon
        ,ArrowLeftCircleIcon
        ,ArrowLeftEndOnRectangleIcon
        ,ArrowLeftOnRectangleIcon
        ,ArrowLeftStartOnRectangleIcon
        ,ArrowLeftIcon
        ,ArrowLongDownIcon
        ,ArrowLongLeftIcon
        ,ArrowLongRightIcon
        ,ArrowLongUpIcon
        ,ArrowPathRoundedSquareIcon
        ,ArrowPathIcon
        ,ArrowRightCircleIcon
        ,ArrowRightEndOnRectangleIcon
        ,ArrowRightOnRectangleIcon
        ,ArrowRightStartOnRectangleIcon
        ,ArrowRightIcon
        ,ArrowSmallDownIcon
        ,ArrowSmallLeftIcon
        ,ArrowSmallRightIcon
        ,ArrowSmallUpIcon
        ,ArrowTopRightOnSquareIcon
        ,ArrowTrendingDownIcon
        ,ArrowTrendingUpIcon
        ,ArrowTurnDownLeftIcon
        ,ArrowTurnDownRightIcon
        ,ArrowTurnLeftDownIcon
        ,ArrowTurnLeftUpIcon
        ,ArrowTurnRightDownIcon
        ,ArrowTurnRightUpIcon
        ,ArrowTurnUpLeftIcon
        ,ArrowTurnUpRightIcon
        ,ArrowUpCircleIcon
        ,ArrowUpLeftIcon
        ,ArrowUpOnSquareStackIcon
        ,ArrowUpOnSquareIcon
        ,ArrowUpRightIcon
        ,ArrowUpTrayIcon
        ,ArrowUpIcon
        ,ArrowUturnDownIcon
        ,ArrowUturnLeftIcon
        ,ArrowUturnRightIcon
        ,ArrowUturnUpIcon
        ,ArrowsPointingInIcon
        ,ArrowsPointingOutIcon
        ,ArrowsRightLeftIcon
        ,ArrowsUpDownIcon
        ,AtSymbolIcon
        ,BackspaceIcon
        ,BackwardIcon
        ,BanknotesIcon
        ,Bars2Icon
        ,Bars3BottomLeftIcon
        ,Bars3BottomRightIcon
        ,Bars3CenterLeftIcon
        ,Bars3Icon
        ,Bars4Icon
        ,BarsArrowDownIcon
        ,BarsArrowUpIcon
        ,Battery0Icon
        ,Battery100Icon
        ,Battery50Icon
        ,BeakerIcon
        ,BellAlertIcon
        ,BellSlashIcon
        ,BellSnoozeIcon
        ,BellIcon
        ,BoldIcon
        ,BoltSlashIcon
        ,BoltIcon
        ,BookOpenIcon
        ,BookmarkSlashIcon
        ,BookmarkSquareIcon
        ,BookmarkIcon
        ,BriefcaseIcon
        ,BugAntIcon
        ,BuildingLibraryIcon
        ,BuildingOffice2Icon
        ,BuildingOfficeIcon
        ,BuildingStorefrontIcon
        ,CakeIcon
        ,CalculatorIcon
        ,CalendarDateRangeIcon
        ,CalendarDaysIcon
        ,CalendarIcon
        ,CameraIcon
        ,ChartBarSquareIcon
        ,ChartBarIcon
        ,ChartPieIcon
        ,ChatBubbleBottomCenterTextIcon
        ,ChatBubbleBottomCenterIcon
        ,ChatBubbleLeftEllipsisIcon
        ,ChatBubbleLeftRightIcon
        ,ChatBubbleLeftIcon
        ,ChatBubbleOvalLeftEllipsisIcon
        ,ChatBubbleOvalLeftIcon
        ,CheckBadgeIcon
        ,CheckCircleIcon
        ,CheckIcon
        ,ChevronDoubleDownIcon
        ,ChevronDoubleLeftIcon
        ,ChevronDoubleRightIcon
        ,ChevronDoubleUpIcon
        ,ChevronDownIcon
        ,ChevronLeftIcon
        ,ChevronRightIcon
        ,ChevronUpDownIcon
        ,ChevronUpIcon
        ,CircleStackIcon
        ,ClipboardDocumentCheckIcon
        ,ClipboardDocumentListIcon
        ,ClipboardDocumentIcon
        ,ClipboardIcon
        ,ClockIcon
        ,CloudArrowDownIcon
        ,CloudArrowUpIcon
        ,CloudIcon
        ,CodeBracketSquareIcon
        ,CodeBracketIcon
        ,Cog6ToothIcon
        ,Cog8ToothIcon
        ,CogIcon
        ,CommandLineIcon
        ,ComputerDesktopIcon
        ,CpuChipIcon
        ,CreditCardIcon
        ,CubeTransparentIcon
        ,CubeIcon
        ,CurrencyBangladeshiIcon
        ,CurrencyDollarIcon
        ,CurrencyEuroIcon
        ,CurrencyPoundIcon
        ,CurrencyRupeeIcon
        ,CurrencyYenIcon
        ,CursorArrowRaysIcon
        ,CursorArrowRippleIcon
        ,DevicePhoneMobileIcon
        ,DeviceTabletIcon
        ,DivideIcon
        ,DocumentArrowDownIcon
        ,DocumentArrowUpIcon
        ,DocumentChartBarIcon
        ,DocumentCheckIcon
        ,DocumentCurrencyBangladeshiIcon
        ,DocumentCurrencyDollarIcon
        ,DocumentCurrencyEuroIcon
        ,DocumentCurrencyPoundIcon
        ,DocumentCurrencyRupeeIcon
        ,DocumentCurrencyYenIcon
        ,DocumentDuplicateIcon
        ,DocumentMagnifyingGlassIcon
        ,DocumentMinusIcon
        ,DocumentPlusIcon
        ,DocumentTextIcon
        ,DocumentIcon
        ,EllipsisHorizontalCircleIcon
        ,EllipsisHorizontalIcon
        ,EllipsisVerticalIcon
        ,EnvelopeOpenIcon
        ,EnvelopeIcon
        ,EqualsIcon
        ,ExclamationCircleIcon
        ,ExclamationTriangleIcon
        ,EyeDropperIcon
        ,EyeSlashIcon
        ,EyeIcon
        ,FaceFrownIcon
        ,FaceSmileIcon
        ,FilmIcon
        ,FingerPrintIcon
        ,FireIcon
        ,FlagIcon
        ,FolderArrowDownIcon
        ,FolderMinusIcon
        ,FolderOpenIcon
        ,FolderPlusIcon
        ,FolderIcon
        ,ForwardIcon
        ,FunnelIcon
        ,GifIcon
        ,GiftTopIcon
        ,GiftIcon
        ,GlobeAltIcon
        
        ,HandRaisedIcon
        ,HandThumbDownIcon
        ,HandThumbUpIcon
        ,HashtagIcon
        ,HeartIcon
        ,HomeIcon
        ,IdentificationIcon
        ,InboxArrowDownIcon
        ,InboxIcon
        ,InformationCircleIcon
        ,KeyIcon
        
        ,LifebuoyIcon
        ,LightBulbIcon
        
        ,LinkIcon
        ,ListBulletIcon
        
        ,LockClosedIcon
        ,LockOpenIcon
        ,MagnifyingGlassCircleIcon
        ,MagnifyingGlassIcon
        ,MapIcon
        ,MegaphoneIcon
        ,MicrophoneIcon
        ,MinusCircleIcon
        ,MinusIcon
        ,MoonIcon
        
        ,NewspaperIcon
        ,NoSymbolIcon
        ,PaperAirplaneIcon
        ,PaperClipIcon
        ,PauseCircleIcon
        ,PauseIcon
        ,PencilSquareIcon
        ,PencilIcon
        
        ,PhoneIcon
        ,PhotoIcon
        ,PlayCircleIcon
        ,PlayPauseIcon
        ,PlayIcon
        ,PlusCircleIcon
        ,PlusIcon
        ,PresentationChartBarIcon
        ,PresentationChartLineIcon
        ,PrinterIcon
        ,PuzzlePieceIcon
        ,QrCodeIcon
        ,QuestionMarkCircleIcon
        ,ReceiptPercentIcon
        
       
        ,RectangleGroupIcon
        ,RectangleStackIcon
        ,RocketLaunchIcon
        
        ,RssIcon
        
        
        ,ScaleIcon
        ,ScissorsIcon
        ,ShareIcon
        ,ShieldCheckIcon
        ,ShieldExclamationIcon
        
        ,SignalIcon
        
        ,SpeakerWaveIcon
        ,SpeakerXMarkIcon
        ,Square2StackIcon
        ,Square3Stack3DIcon
        
        
        ,Squares2X2Icon
        ,SquaresPlusIcon,
        StarIcon,
        StopCircleIcon,
        SunIcon,
        
        
        TableCellsIcon,
        TagIcon,
        
        
        
        
        TicketIcon,
        TrashIcon,
        TrophyIcon,
        TruckIcon,
        TvIcon,
        UserCircleIcon,
        UserGroupIcon,
        UserIcon,
        UsersIcon,
        VariableIcon,
        VideoCameraIcon,
        ViewColumnsIcon,
        ViewfinderCircleIcon,
        WifiIcon,
        WrenchIcon,
        XCircleIcon,
        XMarkIcon}

export const heroIconsNames = ['AcademicCapIcon'
            ,'AdjustmentsHorizontalIcon'
            ,'AdjustmentsVerticalIcon'
            ,'ArchiveBoxArrowDownIcon'
            ,'ArchiveBoxXMarkIcon'
            ,'ArchiveBoxIcon'
            ,'ArrowDownCircleIcon'
            ,'ArrowDownLeftIcon'
            ,'ArrowDownOnSquareStackIcon'
            ,'ArrowDownOnSquareIcon'
            ,'ArrowDownRightIcon'
            ,'ArrowDownTrayIcon'
            ,'ArrowDownIcon'
            ,'ArrowLeftCircleIcon'
            ,'ArrowLeftEndOnRectangleIcon'
            ,'ArrowLeftOnRectangleIcon'
            ,'ArrowLeftStartOnRectangleIcon'
            ,'ArrowLeftIcon'
            ,'ArrowLongDownIcon'
            ,'ArrowLongLeftIcon'
            ,'ArrowLongRightIcon'
            ,'ArrowLongUpIcon'
            ,'ArrowPathRoundedSquareIcon'
            ,'ArrowPathIcon'
            ,'ArrowRightCircleIcon'
            ,'ArrowRightEndOnRectangleIcon'
            ,'ArrowRightOnRectangleIcon'
            ,'ArrowRightStartOnRectangleIcon'
            ,'ArrowRightIcon'
            ,'ArrowSmallDownIcon'
            ,'ArrowSmallLeftIcon'
            ,'ArrowSmallRightIcon'
            ,'ArrowSmallUpIcon'
            ,'ArrowTopRightOnSquareIcon'
            ,'ArrowTrendingDownIcon'
            ,'ArrowTrendingUpIcon'
            ,'ArrowTurnDownLeftIcon'
            ,'ArrowTurnDownRightIcon'
            ,'ArrowTurnLeftDownIcon'
            ,'ArrowTurnLeftUpIcon'
            ,'ArrowTurnRightDownIcon'
            ,'ArrowTurnRightUpIcon'
            ,'ArrowTurnUpLeftIcon'
            ,'ArrowTurnUpRightIcon'
            ,'ArrowUpCircleIcon'
            ,'ArrowUpLeftIcon'
            ,'ArrowUpOnSquareStackIcon'
            ,'ArrowUpOnSquareIcon'
            ,'ArrowUpRightIcon'
            ,'ArrowUpTrayIcon'
            ,'ArrowUpIcon'
            ,'ArrowUturnDownIcon'
            ,'ArrowUturnLeftIcon'
            ,'ArrowUturnRightIcon'
            ,'ArrowUturnUpIcon'
            ,'ArrowsPointingInIcon'
            ,'ArrowsPointingOutIcon'
            ,'ArrowsRightLeftIcon'
            ,'ArrowsUpDownIcon'
            ,'AtSymbolIcon'
            ,'BackspaceIcon'
            ,'BackwardIcon'
            ,'BanknotesIcon'
            ,'Bars2Icon'
            ,'Bars3BottomLeftIcon'
            ,'Bars3BottomRightIcon'
            ,'Bars3CenterLeftIcon'
            ,'Bars3Icon'
            ,'Bars4Icon'
            ,'BarsArrowDownIcon'
            ,'BarsArrowUpIcon'
            ,'Battery0Icon'
            ,'Battery100Icon'
            ,'Battery50Icon'
            ,'BeakerIcon'
            ,'BellAlertIcon'
            ,'BellSlashIcon'
            ,'BellSnoozeIcon'
            ,'BellIcon'
            ,'BoldIcon'
            ,'BoltSlashIcon'
            ,'BoltIcon'
            ,'BookOpenIcon'
            ,'BookmarkSlashIcon'
            ,'BookmarkSquareIcon'
            ,'BookmarkIcon'
            ,'BriefcaseIcon'
            ,'BugAntIcon'
            ,'BuildingLibraryIcon'
            ,'BuildingOffice2Icon'
            ,'BuildingOfficeIcon'
            ,'BuildingStorefrontIcon'
            ,'CakeIcon'
            ,'CalculatorIcon'
            ,'CalendarDateRangeIcon'
            ,'CalendarDaysIcon'
            ,'CalendarIcon'
            ,'CameraIcon'
            ,'ChartBarSquareIcon'
            ,'ChartBarIcon'
            ,'ChartPieIcon'
            ,'ChatBubbleBottomCenterTextIcon'
            ,'ChatBubbleBottomCenterIcon'
            ,'ChatBubbleLeftEllipsisIcon'
            ,'ChatBubbleLeftRightIcon'
            ,'ChatBubbleLeftIcon'
            ,'ChatBubbleOvalLeftEllipsisIcon'
            ,'ChatBubbleOvalLeftIcon'
            ,'CheckBadgeIcon'
            ,'CheckCircleIcon'
            ,'CheckIcon'
            ,'ChevronDoubleDownIcon'
            ,'ChevronDoubleLeftIcon'
            ,'ChevronDoubleRightIcon'
            ,'ChevronDoubleUpIcon'
            ,'ChevronDownIcon'
            ,'ChevronLeftIcon'
            ,'ChevronRightIcon'
            ,'ChevronUpDownIcon'
            ,'ChevronUpIcon'
            ,'CircleStackIcon'
            ,'ClipboardDocumentCheckIcon'
            ,'ClipboardDocumentListIcon'
            ,'ClipboardDocumentIcon'
            ,'ClipboardIcon'
            ,'ClockIcon'
            ,'CloudArrowDownIcon'
            ,'CloudArrowUpIcon'
            ,'CloudIcon'
            ,'CodeBracketSquareIcon'
            ,'CodeBracketIcon'
            ,'Cog6ToothIcon'
            ,'Cog8ToothIcon'
            ,'CogIcon'
            ,'CommandLineIcon'
            ,'ComputerDesktopIcon'
            ,'CpuChipIcon'
            ,'CreditCardIcon'
            ,'CubeTransparentIcon'
            ,'CubeIcon'
            ,'CurrencyBangladeshiIcon'
            ,'CurrencyDollarIcon'
            ,'CurrencyEuroIcon'
            ,'CurrencyPoundIcon'
            ,'CurrencyRupeeIcon'
            ,'CurrencyYenIcon'
            ,'CursorArrowRaysIcon'
            ,'CursorArrowRippleIcon'
            ,'DevicePhoneMobileIcon'
            ,'DeviceTabletIcon'
            ,'DivideIcon'
            ,'DocumentArrowDownIcon'
            ,'DocumentArrowUpIcon'
            ,'DocumentChartBarIcon'
            ,'DocumentCheckIcon'
            ,'DocumentCurrencyBangladeshiIcon'
            ,'DocumentCurrencyDollarIcon'
            ,'DocumentCurrencyEuroIcon'
            ,'DocumentCurrencyPoundIcon'
            ,'DocumentCurrencyRupeeIcon'
            ,'DocumentCurrencyYenIcon'
            ,'DocumentDuplicateIcon'
            ,'DocumentMagnifyingGlassIcon'
            ,'DocumentMinusIcon'
            ,'DocumentPlusIcon'
            ,'DocumentTextIcon'
            ,'DocumentIcon'
            ,'EllipsisHorizontalCircleIcon'
            ,'EllipsisHorizontalIcon'
            ,'EllipsisVerticalIcon'
            ,'EnvelopeOpenIcon'
            ,'EnvelopeIcon'
            ,'EqualsIcon'
            ,'ExclamationCircleIcon'
            ,'ExclamationTriangleIcon'
            ,'EyeDropperIcon'
            ,'EyeSlashIcon'
            ,'EyeIcon'
            ,'FaceFrownIcon'
            ,'FaceSmileIcon'
            ,'FilmIcon'
            ,'FingerPrintIcon'
            ,'FireIcon'
            ,'FlagIcon'
            ,'FolderArrowDownIcon'
            ,'FolderMinusIcon'
            ,'FolderOpenIcon'
            ,'FolderPlusIcon'
            ,'FolderIcon'
            ,'ForwardIcon'
            ,'FunnelIcon'
            ,'GifIcon'
            ,'GiftTopIcon'
            ,'GiftIcon'
            ,'GlobeAltIcon'
            
            ,'HandRaisedIcon'
            ,'HandThumbDownIcon'
            ,'HandThumbUpIcon'
            ,'HashtagIcon'
            ,'HeartIcon'
            ,'HomeIcon'
            ,'IdentificationIcon'
            ,'InboxArrowDownIcon'
            ,'InboxIcon'
            ,'InformationCircleIcon'
            ,'KeyIcon'
            ,'LifebuoyIcon'
            ,'LightBulbIcon'
            ,'LinkIcon'
            ,'ListBulletIcon'
            ,'LockClosedIcon'
            ,'LockOpenIcon'
            ,'MagnifyingGlassCircleIcon'
            ,'MagnifyingGlassIcon'
            ,'MapIcon'
            ,'MegaphoneIcon'
            ,'MicrophoneIcon'
            ,'MinusCircleIcon'
            ,'MinusIcon'
            ,'MoonIcon'
            ,'NewspaperIcon'
            ,'NoSymbolIcon'
            ,'PaperAirplaneIcon'
            ,'PaperClipIcon'
            ,'PauseCircleIcon'
            ,'PauseIcon'
            ,'PencilSquareIcon'
            ,'PencilIcon'
            ,'PhoneIcon'
            ,'PhotoIcon'
            ,'PlayCircleIcon'
            ,'PlayPauseIcon'
            ,'PlayIcon'
            ,'PlusCircleIcon'
            ,'PlusIcon'
            ,'PresentationChartBarIcon'
            ,'PresentationChartLineIcon'
            ,'PrinterIcon'
            ,'PuzzlePieceIcon'
            ,'QrCodeIcon'
            ,'QuestionMarkCircleIcon'
            ,'ReceiptPercentIcon'
            
            ,'RectangleGroupIcon'
            ,'RectangleStackIcon'
            ,'RocketLaunchIcon'
       
            ,'RssIcon'

            ,'ScaleIcon'
            ,'ScissorsIcon'
            ,'ShareIcon'
            ,'ShieldCheckIcon'
            ,'ShieldExclamationIcon'

            ,'SignalIcon'

            ,'SpeakerWaveIcon'
            ,'SpeakerXMarkIcon'
            ,'Square2StackIcon'
            ,'Square3Stack3DIcon'

            
            ,'Squares2X2Icon'
            ,'SquaresPlusIcon',
            'StarIcon',
            'StopCircleIcon',
            'SunIcon',

            'TableCellsIcon',
            'TagIcon',
            
            'TicketIcon',
            'TrashIcon',
            'TrophyIcon',
            'TruckIcon',
            'TvIcon',
            
            'UserCircleIcon',
            'UserGroupIcon',
            'UserIcon',
            'UsersIcon',
            'VariableIcon',
            'VideoCameraIcon',
            'ViewColumnsIcon',
            'ViewfinderCircleIcon',
            'WifiIcon',
            'WrenchIcon',
            'XCircleIcon',
            'XMarkIcon'
        ]

function HeroIcon(props) {
    const IconToRender = heroIcons[props.iconTitle];
    return (<>
       <span onClick={props.onClick?props.onClick:()=>{}}><IconToRender className={`${props.style?props.style:"h-6 w-6"}`}   /></span>
    </>);
}


export default HeroIcon;


